[[polyhedral]]
arch = "aarch64"
git-tree-sha1 = "60574a3e6f50a93636c065536c384f1679a01c39"
os = "macos"

    [[polyhedral.download]]
    sha256 = "bc2b3d7792dbbbee44ab44a205e12c1541623ffff88f7099150648fe0acdaf91"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.aarch64-apple-darwin.tar.gz"
[[polyhedral]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69dbe34ae447d34c93f62b784d18ead9544e34af"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "8011b53a601fd1d8f35dd921327aed5de1aab1ad038c0cbf917676f69884d710"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[polyhedral]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e70d72a340a8dfea4826504a7affeb0e2ca1726"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "fb1ce2450d1b01dcb4e7cc9c3fef08d31b6d747c18b8f148e16dab241fa1f4cc"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[polyhedral]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5688f6ef67f3ab9a99ba892adc338b4df7b92c95"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "3823ef3590e7a730ed5e17c2312c059eb12b551c9b2d8aa7cf6c49390dc07077"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[polyhedral]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07453f9ca4f3c21509684013e113b5fb8b1a2baa"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "720c0912b3fe77668bb90f9fd1aefc95d986bc65a371d26266f64d44417d1f89"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[polyhedral]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "934636d84fa8d9e9ab75c2c54b44b6214ae0fddd"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "c3afc23929f88ebd2d0295e032d794f250a13b73ac793b563b0f2ef3b2a37e6d"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[polyhedral]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "340b51153a951f9d6a655bf4a831221c3e57c8bb"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "a38a8e517c94b6d7200b822c7ddc621580c2c71b4a776219136e62d5592464a2"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[polyhedral]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7f57297cac0181a8ee58c61a791a145dc2e45f7"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "c5059004e002461e80814812f41e6b8b2b50b318b7e218650149bd9dee0ba5e9"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[polyhedral]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "377f729cef754d2736e9731d7a715a78a289cc85"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "fcbef8ac35e8c3d18fa0dcc87480ef940ff2301ff76f4206a34abc72c3858874"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[polyhedral]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "209ad0b69b36b27fe5dcd22c08b845203b05cb4e"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "fd4015cd66c1d3866ee3d488404bfd3dd9cb276e979c466a029d039a6812d8ea"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[polyhedral]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e0cdf7a63f65745120808ba416050efc7079ea9"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "4d841c3bc63fe308159296055f4c07b305d1e8709cbe6e4a1a50d3669832b817"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[polyhedral]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ba67275e6f0fc3ae4be3c03f1ae07731d3cdd5e"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "148c2ac0decc1f1545dac87f6d8c2615162493a850402402891a9143dedcb957"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[polyhedral]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbdcf15de3dc3f42cfb24958836763c8a753ff1e"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "4c67a3fa8222b67fc539cad979dc1392bd3dd5639d0c5a735212056665d0d747"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[polyhedral]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a940fd867181215797ac924c6e4683cb22277260"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "0274b70d99743932931b438108799a3fb9f39c0418d88b0f40e63e7876542245"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.i686-linux-gnu-cxx03.tar.gz"
[[polyhedral]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98259b6a92a43c7df65acdf93d00611314a1275a"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "fe1c2c0b5fcafbcaf841d10a29813285cf55d6a6fc42bd95369a0ea73a75149f"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.i686-linux-gnu-cxx11.tar.gz"
[[polyhedral]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46534a98ac57f99c2e60ced1fc9fc3038be57e9c"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "f8311f6c10dc6ade48652b25217ddf1ceca3008ed2266b06cb62aeee5164f8c5"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.i686-linux-musl-cxx03.tar.gz"
[[polyhedral]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce35df2070fadeb56d6bb266a7b58bbb150afdfc"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "684d79aebf34f3d853f45f97637574e3bca337ca18a834f38ac067d68c2ff3b5"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.i686-linux-musl-cxx11.tar.gz"
[[polyhedral]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bf11f0792e901924ff8a60c33b96470b8c0c89c"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "659fe4a29119c8b355ad25f9e372e561e40bddcb727464057daca43f6f72b30d"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[polyhedral]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76c922149831570cf8595b8dc4dd9e95c76d52c2"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "fb27bf747dab97b86a204abe85885ac60cc09d42318756dc5dc59e8232e9c195"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[polyhedral]]
arch = "x86_64"
git-tree-sha1 = "da11e4e107cc344b8474bdb057a7745d2455f133"
os = "macos"

    [[polyhedral.download]]
    sha256 = "5628edfe0413343883b7c9d97d76379c14e1f8183a8ba05e088a5d503c173ad0"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.x86_64-apple-darwin.tar.gz"
[[polyhedral]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5e841124fe07c4f76912ccc7530010fb3acf37c"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "1dd61c67492a3cceba2532de3007f52b8c13d0847cbdde6836b3ab9e87ee205b"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[polyhedral]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11416fa2351b696e5c1b9daf854bc25cfdedc874"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "00219fd750272afc828a8c2a18330001987e593d020d571459b00f6841c46b21"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[polyhedral]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b53fc415a7cf677781d374389f6acf6370748c8"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "4cfa52c36c32cfe9a4f932b636d6168b4efbf5ab75b1ed34521303472bf76d6a"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[polyhedral]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1c77f0a4d750793a2600e2734820c435d2169b5"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "bca8a6033fdbcce2d90643f6cf41eb5f89d0d4ef41a42631a996297632db2762"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[polyhedral]]
arch = "x86_64"
git-tree-sha1 = "38e62fcf4f045f2873549a49c6d16c4bce507272"
os = "freebsd"

    [[polyhedral.download]]
    sha256 = "310962341d5397eb587a9d761ce8c42bf9d1586c90f3f0b88902424317386df6"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.3.0+0/polyhedral.v0.3.0.x86_64-unknown-freebsd.tar.gz"
