[[polyhedral]]
arch = "aarch64"
git-tree-sha1 = "2fd6315dc5b7feb165bdb0c9a42e2789e821c987"
os = "macos"

    [[polyhedral.download]]
    sha256 = "f0b5a10385257de013e4f3d00b31e92375ed35ae62b68479f2cd08d5b32f3f7a"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.aarch64-apple-darwin.tar.gz"
[[polyhedral]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a08df2d6349ad85b010659eb80bc2d139c0d7dd"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "a140c26e1e99e5e0d677e279d5ed1f11fe82ce6d1caa27148f2aee1b55287c07"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[polyhedral]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a8f93ceb4c3b28a25089ecf62b3726db6b663b3"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "02ad946055e71cb4b90e8056e0a07ad5f843cd5f0ce5d6f569b0302ee20bc0b0"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[polyhedral]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84f8c45cdcedccfa2e77bb09016b799ef9a1d274"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "6c43eae6cff707fa9c7edae702ee8a08b734832666567918bf12d614de57eae6"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[polyhedral]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "565971452db7d6141c18d7f1d1db690b1c6a8f96"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "5dd0cc641c73c54c6bff0560048196b354b5798d7a678f765fa3b97e54e230e3"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[polyhedral]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85d07e81371dd467b7592244b196cb1fe45a0c09"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "d8ede4c04c419e1165c429dd447b647c3e585714e6fb3d2564a9d90174ad9cb8"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[polyhedral]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0628a68d08b0efd1a6289a3b69959fae6e62c449"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "f13b68a705c60c75d545365b136509d05586b19d187c9d56b4b3986a87a373e5"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[polyhedral]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0569a7419ac94fe7ee3ad6f8e293070462547de7"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "260ef81dbf57753848321944308cc12eb5d190b075f4fe4dd6ccb5f9a94a5e25"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[polyhedral]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "796dffb2c9319b0ead531315dae4dbbb7ba4cdb4"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "a9b1007d3c9b12e03a145687e7ba1cecc656f6e212146d43a51b9deee9ff3498"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[polyhedral]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3cb12aa8a4082b6b099da3e21461876d29169c5"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "8bf339e0fd976664a5c362d5545679c3e2758bc68e5e9c9e2eeb94d9f6c34d03"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[polyhedral]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f27b92af19a007dc7303fdc22c877ae68c0d479"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "450d6955d23f1d3c0eaf3dd8afec072efd85e9d9bf0d73d4a83919fae1e0264d"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[polyhedral]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7452d681d9f8f008a3019bca4f5a528a84a8cb46"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "6267a632ba81f86888001e2fcdd7c9af834b66910fa2161ddfe6be2293f4d802"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[polyhedral]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d114ea9bca499cc7ea03fad5c7fbd063f534e54b"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "5ee371f51a6cee0bacc7a2863a248ce4380060fa87a15057e547beee72f9c2f5"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[polyhedral]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "316cd0ff5bc8c2fa251f872cb2ae50a372a5f3f5"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "cebf7c360a6582e7951531a4cbbc3bf4bd7fab97eb6f5dcdf154f6f8a6096e2a"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.i686-linux-gnu-cxx03.tar.gz"
[[polyhedral]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6e487ed8e54cee2d730ba60205da47ea83c649b"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "523f6897a0a1e9e845c23f131032a606dd17a82738e9628174015e4161f342fe"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.i686-linux-gnu-cxx11.tar.gz"
[[polyhedral]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "806ea79fb248929fbc0bf7b1334381f38fd95452"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "9df2fb19100ca6a9d044511d06f8b99510531c78d5824cf065a6a380b123b2b1"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.i686-linux-musl-cxx03.tar.gz"
[[polyhedral]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa7822e661b4943e4506f282c8f88f60dd055074"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "311abc048dca5af1c3537b5c9103fbb71ac964284fd248f08c4fed7573f40866"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.i686-linux-musl-cxx11.tar.gz"
[[polyhedral]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96417d4aa84ee3e108923c8731a18da05af94cd8"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "546fd51f19d285578c72a179bbd37e74e3ee996fbb2224135422036660725bb0"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[polyhedral]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4babadaf9c0e74222d483baaf6d3d30df7bc8d7c"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "08a019227450f36aabcbf1b3817c0a3c3ec01b4fab4544951098035271484fc5"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[polyhedral]]
arch = "x86_64"
git-tree-sha1 = "95c853f9b662473bfbb13830641f6d5c81c7cf20"
os = "macos"

    [[polyhedral.download]]
    sha256 = "5c8e8a140efe800140314dd66a3d9badc17b06396b609194bd8ed2dbc216b1f5"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.x86_64-apple-darwin.tar.gz"
[[polyhedral]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c27726540c9caaab88495eb34c183205b217993a"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "b391c94c6a378714ea1b340dbbab53aa757d51973e134c6c881c28c40c12fe9d"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[polyhedral]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13b630fc39a91809a2b6b80cebab9991101595cc"
libc = "glibc"
os = "linux"

    [[polyhedral.download]]
    sha256 = "0a0c6a41e92147725b006baced104e5dffc1d9dfaef5e1f203a463cc6b74fca4"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[polyhedral]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84bdb2dcf00b6a2d1dc5aa1404cc33dc5c55652a"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "24a096afc319ed80af92cb546794a6fef70d832f0ce787b452f818f536f45fdf"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[polyhedral]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "424abde8675ed74c956117c0c12dd332d583f4a1"
libc = "musl"
os = "linux"

    [[polyhedral.download]]
    sha256 = "e3c075475ecb3e5bdbd50621787db8f383cea08a40f9710b3cd16a2ca4729603"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[polyhedral]]
arch = "x86_64"
git-tree-sha1 = "19463ea9197c2640fa6979379d780e93d7127fcf"
os = "freebsd"

    [[polyhedral.download]]
    sha256 = "19334db9c6ea7ad38c79760f1c88dc95da5b87f77be88ffd0411311f19c16414"
    url = "https://github.com/JuliaBinaryWrappers/polyhedral_jll.jl/releases/download/polyhedral-v0.2.0+0/polyhedral.v0.2.0.x86_64-unknown-freebsd.tar.gz"
